import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np
from fpdf import FPDF
import base64

# --- 1. إعدادات الصفحة والجماليات ---
st.set_page_config(page_title="Sidra Utilities Intelligence", layout="wide")

st.markdown("""
    <style>
    .stMetric { background-color: #ffffff; border: 1px solid #e0e0e0; padding: 15px; border-radius: 10px; box-shadow: 2px 2px 5px rgba(0,0,0,0.05); }
    .forecast-box { background-color: #e8f5e9; border: 1px dashed #2e7d32; padding: 15px; border-radius: 10px; text-align: center; font-weight: bold; }
    </style>
    """, unsafe_allow_html=True)

if 'lang' not in st.session_state: st.session_state.lang = 'Arabic'
def toggle_lang(): st.session_state.lang = 'English' if st.session_state.lang == 'Arabic' else 'Arabic'

translations = {
    'Arabic': {
        'title': "📊 نظام سدرة الذكي الشامل",
        'lang_btn': "Switch to English",
        'all_period': "السنة كاملة",
        'summary': "📋 مؤشرات الأداء والإنتاج (KPIs)",
        'forecast': "🔮 التنبؤ بنهاية الشهر",
        'pdf_btn': "📄 تحميل تقرير PDF الشهري",
        'footer': "Done by Maintenance Department (Utilities)"
    },
    'English': {
        'title': "📊 SIDRA COMPREHENSIVE SYSTEM",
        'lang_btn': "التحويل للعربية",
        'all_period': "Full Year",
        'summary': "📋 Production & Efficiency KPIs",
        'forecast': "🔮 Monthly Forecast",
        'pdf_btn': "📄 Download Monthly PDF Report",
        'footer': "Done by Maintenance Department (Utilities)"
    }
}
l = translations[st.session_state.lang]

# --- 2. وظيفة إنشاء تقرير PDF ---
def create_pdf(df, prod_qty, selected_month):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    
    # Header
    pdf.cell(190, 10, f"AL-SIDRA UTILITIES REPORT - {selected_month}", ln=True, align='C')
    pdf.set_font("Arial", '', 12)
    pdf.cell(190, 10, "Maintenance Department (Utilities Section)", ln=True, align='C')
    pdf.ln(10)
    
    # Metrics Table
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(95, 10, "Metric Description", 1, 0, 'C', True)
    pdf.cell(95, 10, "Value", 1, 1, 'C', True)
    
    avg_prod = prod_qty / 30
    metrics = [
        ("Total Electricity Consumption", f"{df['ELEC'].sum():,.0f} kWh"),
        ("Total LPG Consumption", f"{df['LPG'].sum():,.0f} kg"),
        ("Total Water Intake", f"{df['W_IN'].sum():,.0f} m3"),
        ("Electricity Efficiency", f"{(df['ELEC'].mean()/avg_prod):.3f} kWh/kg"),
        ("LPG Efficiency", f"{(df['LPG'].mean()/avg_prod):.4f} kg/kg"),
        ("Water Loss Percentage", f"{((df['W_IN'].sum()-df['W_OUT'].sum())/df['W_IN'].sum()*100):.1f}%")
    ]
    
    for m, v in metrics:
        pdf.cell(95, 10, m, 1)
        pdf.cell(95, 10, v, 1, 1, 'C')
        
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(190, 10, "Generated by Al-Sidra Intelligence App - 2025", align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- 3. القائمة الجانبية ---
with st.sidebar:
    try: st.image("al sidra new.jpg", use_container_width=True)
    except: st.subheader("AL-SIDRA")
    st.button(l['lang_btn'], on_click=toggle_lang)
    st.markdown("---")
    uploaded_file = st.file_uploader("Upload XLSX", type=['xlsx'])
    prod_qty = st.number_input("Total Production (KG)", min_value=1.0, value=150000.0)

# --- 4. المعالجة والعرض ---
if uploaded_file:
    xl = pd.ExcelFile(uploaded_file)
    dfs = [xl.parse(s).assign(MONTH=s) for s in xl.sheet_names]
    full_df = pd.concat(dfs, ignore_index=True)
    full_df.columns = [str(c).strip().upper() for c in full_df.columns]
    full_df.rename(columns={'DAY': 'DATE'}, inplace=True)
    
    selected_period = st.selectbox("Select Month", [l['all_period']] + list(full_df['MONTH'].unique()))
    df = full_df if selected_period == l['all_period'] else full_df[full_df['MONTH'] == selected_period]
    
    # جلب البيانات
    df['ELEC'] = pd.to_numeric(df.get('ELEC', 0), errors='coerce').fillna(0)
    df['LPG'] = pd.to_numeric(df.get('LPG', 0), errors='coerce').fillna(0)
    df['W_IN'] = pd.to_numeric(df.get('WATER REC', 0), errors='coerce').fillna(0)
    df['W_OUT'] = pd.to_numeric(df.get('SANIT', 0), errors='coerce').fillna(0)

    # زر الـ PDF
    if st.button(l['pdf_btn']):
        pdf_data = create_pdf(df, prod_qty, selected_period)
        b64 = base64.b64encode(pdf_data).decode()
        href = f'<a href="data:application/octet-stream;base64,{b64}" download="Sidra_Report_{selected_period}.pdf">Click here to download PDF</a>'
        st.markdown(href, unsafe_allow_html=True)

    # عرض الـ KPIs والرسوم (كما في الكود السابق)
    st.subheader(l['summary'])
    avg_p = prod_qty / 30
    c1, c2, c3 = st.columns(3)
    c1.metric("Elec/KG", f"{(df['ELEC'].mean()/avg_p):.3f} kWh")
    c2.metric("LPG/KG", f"{(df['LPG'].mean()/avg_p):.4f} kg")
    c3.metric("Water Loss", f"{(df['W_IN'].sum()-df['W_OUT'].sum()):,.0f} m3")

    st.plotly_chart(px.line(df, x='DATE', y=['ELEC', 'LPG'], title="Consumption Trend"), use_container_width=True)
